apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: bookmyshow-prod
  region: ap-south-1
  version: "1.29"
vpc:
  id: "vpc-0b24f47679ad00bdd"  # Your existing lab-vpc
  cidr: "10.0.0.0/16"
  subnets:
    public:
      ap-south-1a:
        id: "subnet-0f40e2aca9c0e6fcb"
        az: "ap-south-1a"
      ap-south-1c:
        id: "subnet-0560a22ee34f0794a"
        az: "ap-south-1c"
managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: false
    labels:
      role: worker
    tags:
      Project: bookmyshow
      Environment: production
iam:
  withOIDC: true
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
